apiVersion: v1
kind: Service
metadata:
  name: wordpress
  namespace: app
spec:
  type: NodePort
  selector:
    app: wordpress
    tier: frontend
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: http-port
  
