apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deployment
  namespace: app
  labels:
    app: wordpress
    tier: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wordpress
      tier: frontend
  template:
    metadata:
      labels:
        app: wordpress
        tier: frontend
    spec:
      containers:
        - name: contenedor-wordpress
          image: wordpress:beta-php8.2-fpm-alpine
          ports:
            - containerPort: 80
              name: http-port
          env:
            - name: WORDPRESS_DB_HOST
              value: mysql
            - name: WORDPRESS_DB_USER
              valueFrom:
                configMapKeyRef:
                  name: cm-bd-wordpress
                  key: bd_user
            - name: WORDPRESS_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: scr-bd-wordpress
                  key: bd_userpassword
            - name: WORDPRESS_DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: cm-bd-wordpress
                  key: bd_dbname
          volumeMounts:
            - name: wordpress-persistent-storage
              mountPath: /var/www/html         
      volumes:
        - name: wordpress-persistent-storage
          persistentVolumeClaim:
            claimName: wp-pvc      
