apiVersion: v1
kind: ConfigMap 
metadata:
  name: prometheus-cm
  namespace: devops-tools
data: 
  prometheus.yml: |
    global:
      scrape_interval: 15s
    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']
# Agregar con la coma al targets  --> , '192.168.1.132:9100'
