apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: devops-tools
  labels:
    app: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
        - name: prometheus
          image: prom/prometheus
          resources:
            limits:
              memory: "900Mi"
              cpu: "1000m"
            requests:
              memory: "500Mi"
              cpu: "500m" 
          args:
          - --config.file=/etc/prometheus/prometheus.yml
          - --storage.tsdb.path=/prometheus
          ports:
          - containerPort: 9090
            name: prometheus
          volumeMounts:
          - name: prometheus-data
            mountPath: /prometheus  
          - name: prometheus-conf
            mountPath: /etc/prometheus
          imagePullPolicy: "Always"
      volumes:
      - name: prometheus-data
        persistentVolumeClaim:
          claimName: prometheus-data-pvc
      - name: prometheus-conf
        configMap:
          name: prometheus-cm    
     
