apiVersion: v1
kind: Service
metadata:
  name: prometheus-service
  namespace: devops-tools
  labels:
    app: prometheus
spec:
  ports:
    - port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: prometheus  
  type: NodePort
