apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: gitea
  name: gitea
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gitea
  template:
    metadata:
      labels:
        app: gitea
    spec:
      volumes:
        - name: gitea-volume
          persistentVolumeClaim:
            claimName: gitea-pvc-3g
      containers:
        - image: gitea/gitea:1.21.2
          name: gitea
          volumeMounts:
            - mountPath: "/data"
              name: gitea-volume
          env:
            - name: USER_UID
              value: "1000"
            - name: USER_GID
              value: "1000"
            - name:  GITEA__database__DB_TYPE
              value: "mysql"
            - name:  GITEA__database__HOST
              value: "mysql-clip.default.svc.cluster.local:3306"
            - name: GITEA__database__NAME
              value: "gitea"
            - name: GITEA__database__USER
              value: "giteauser"
            - name: GITEA__database__PASSWD
              value: "giteapass"
          ports:
          - containerPort: 3000
            name: gitea
