apiVersion: v1
kind: Service
metadata:
  name: gitea-np
spec:
  type: NodePort
  ports:
  - name: http
    port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 31000
  selector:
    app: gitea
