apiVersion: v1
kind: PersistentVolume
metadata:
  name: grafana-pvo
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
    - uid=472
    - gid=472
  nfs:
    path: /home/milo/nfs-serv/grafana
    server: 192.168.1.63
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-pvcl
  labels:
    app: grafana
spec:
  storageClassName: nfs
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 4Gi
---
