apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-2g
spec:
  claimRef:
    name: jenkins-pvc-2g
    namespace: devops-tools
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /home/milo/nfs-serv/jenkins
    server: 192.168.1.63
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc-2g
  namespace: devops-tools
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi
  storageClassName: nfs
