apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-5g
spec:
  claimRef:
    name: jenkins-pvc-5g
    namespace: devops-tools
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /home/milo/nfs/jenkins
    server: 10.110.0.3
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc-5g
  namespace: devops-tools
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
