apiVersion: v1
kind: PersistentVolume
metadata:
  name: jenkins-pv-3g
spec:
  claimRef:
    name: jenkins-pvc-3g
    namespace: devops-tools
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /home/milo/nfs-serv/jenkins
    server: 192.168.1.132
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jenkins-pvc-3g
  namespace: devops-tools
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi
