apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: wordpress
    tier: mysql
spec:
  selector:
    app: wordpress
    tier: mysql
  type: ClusterIP
  ports:
  - name: service-bd
    port: 3306
    targetPort: db-port
